# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wuhan/study-code/gitRepository/dataStructureAlgorithmStudy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wuhan/study-code/gitRepository/dataStructureAlgorithmStudy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuhan/study-code/gitRepository/dataStructureAlgorithmStudy/CMakeFiles /home/wuhan/study-code/gitRepository/dataStructureAlgorithmStudy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuhan/study-code/gitRepository/dataStructureAlgorithmStudy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dataStructureAlgorithmStudy

# Build rule for target.
dataStructureAlgorithmStudy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dataStructureAlgorithmStudy
.PHONY : dataStructureAlgorithmStudy

# fast build rule for target.
dataStructureAlgorithmStudy/fast:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/build
.PHONY : dataStructureAlgorithmStudy/fast

linearStructure_链表.o: linearStructure_链表.cpp.o

.PHONY : linearStructure_链表.o

# target to build an object file
linearStructure_链表.cpp.o:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_链表.cpp.o
.PHONY : linearStructure_链表.cpp.o

linearStructure_链表.i: linearStructure_链表.cpp.i

.PHONY : linearStructure_链表.i

# target to preprocess a source file
linearStructure_链表.cpp.i:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_链表.cpp.i
.PHONY : linearStructure_链表.cpp.i

linearStructure_链表.s: linearStructure_链表.cpp.s

.PHONY : linearStructure_链表.s

# target to generate assembly for a file
linearStructure_链表.cpp.s:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_链表.cpp.s
.PHONY : linearStructure_链表.cpp.s

linearStructure_顺序表.o: linearStructure_顺序表.cpp.o

.PHONY : linearStructure_顺序表.o

# target to build an object file
linearStructure_顺序表.cpp.o:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_顺序表.cpp.o
.PHONY : linearStructure_顺序表.cpp.o

linearStructure_顺序表.i: linearStructure_顺序表.cpp.i

.PHONY : linearStructure_顺序表.i

# target to preprocess a source file
linearStructure_顺序表.cpp.i:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_顺序表.cpp.i
.PHONY : linearStructure_顺序表.cpp.i

linearStructure_顺序表.s: linearStructure_顺序表.cpp.s

.PHONY : linearStructure_顺序表.s

# target to generate assembly for a file
linearStructure_顺序表.cpp.s:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/linearStructure_顺序表.cpp.s
.PHONY : linearStructure_顺序表.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/main.cpp.s
.PHONY : main.cpp.s

set_funcs.o: set_funcs.cpp.o

.PHONY : set_funcs.o

# target to build an object file
set_funcs.cpp.o:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/set_funcs.cpp.o
.PHONY : set_funcs.cpp.o

set_funcs.i: set_funcs.cpp.i

.PHONY : set_funcs.i

# target to preprocess a source file
set_funcs.cpp.i:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/set_funcs.cpp.i
.PHONY : set_funcs.cpp.i

set_funcs.s: set_funcs.cpp.s

.PHONY : set_funcs.s

# target to generate assembly for a file
set_funcs.cpp.s:
	$(MAKE) -f CMakeFiles/dataStructureAlgorithmStudy.dir/build.make CMakeFiles/dataStructureAlgorithmStudy.dir/set_funcs.cpp.s
.PHONY : set_funcs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dataStructureAlgorithmStudy"
	@echo "... linearStructure_链表.o"
	@echo "... linearStructure_链表.i"
	@echo "... linearStructure_链表.s"
	@echo "... linearStructure_顺序表.o"
	@echo "... linearStructure_顺序表.i"
	@echo "... linearStructure_顺序表.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... set_funcs.o"
	@echo "... set_funcs.i"
	@echo "... set_funcs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

